"use strict";

/** Default notebook decision cell. Shared market helpers live in Market.verdict. */
export const DEFAULT_NOTEBOOK_DECISION_CELL_LINES = [
  "module Main exposing (main)",
  "import Market exposing (..)",
  "import Loop exposing (..)",
  "",
  "-- Producer cell: evaluate the current asset list, persist each signal, and",
  "-- keep a rolling price history (capped at the last 240 points) in the shared",
  "-- market cache so the simulator cell can back-test it. Loops forever via the",
  "-- built-in sleep effect (loopEvery) — press Stop on the cell/nav to end it.",
  "-- Market data/indicators/scoring are imported from the visible Market.verdict cell.",
  "",
  "-- Bounded append: keep only the last N prices so the history (and everything",
  "-- that reads it) stays fast no matter how long the loop runs.",
  "boundedHistCsv : Int -> String -> Int -> String",
  "boundedHistCsv n csv px =",
  "  foldl(joinCsvInt, \"\", lastN(n, append(parseCsvInts(csv), px)))",
  "",
  "joinCsvInt : String -> Int -> String",
  "joinCsvInt acc n =",
  "  if strLength(acc) == 0 then fromInt(n) else strConcat(acc, strConcat(\",\", fromInt(n)))",
  "",
  "notifyTelegram : String -> String -> String -> String",
  "notifyTelegram token chatId text =",
  "  if strLength(token) < 10 then \"telegram:skip(no token)\"",
  "  else if strLength(chatId) < 3 then \"telegram:skip(no chat)\"",
  "  else httpPost(",
  "    strConcat(\"https://api.telegram.org/bot\", strConcat(token, \"/sendMessage\")),",
  "    text",
  "  ).body",
  "",
  "decisionForAsset : Int -> Int -> String -> List Int -> Json",
  "decisionForAsset threshold bias sym window =",
  "  let px = lastInt(window) in",
  "  let mean = meanOf(window) in",
  "  let sd = stddevOf(window) in",
  "  let z = zScoreOf(window) in",
  "  let emaFast = emaOf(5, window) in",
  "  let emaSlow = emaOf(20, window) in",
  "  let slope = slopeOf(window) in",
  "  let rangePos = rangePosOf(window) in",
  "  let mom = momentumOf(window) in",
  "  let sc = scoreOf(z, emaFast, emaSlow, slope, mom, bias) in",
  "  let d = decisionFromScore(sc, threshold) in",
  "  { symbol = sym, decision = d, score = sc, priceCents = px,",
  "    mean = mean, stddev = sd, zscore = z, emaFast = emaFast, emaSlow = emaSlow,",
  "    slope = slope, rangePos = rangePos, momentum = mom, samples = length(window) }",
  "",
  "explainDecision : Int -> Int -> String -> String",
  "explainDecision s threshold d =",
  "  if d == \"BUY\" then joinStr([\"score \", fromInt(s), \" >= threshold \", fromInt(threshold), \" => BUY\"])",
  "  else if d == \"SELL\" then joinStr([\"score \", fromInt(s), \" <= -threshold \", fromInt(threshold), \" => SELL\"])",
  "  else joinStr([\"score \", fromInt(s), \" within +/-\", fromInt(threshold), \" => HOLD\"])",
  "",
  "assetDetail : Json -> Int -> String -> String -> String",
  "assetDetail row threshold savedId alertStatus =",
  "  joinStr([",
  "    \"* \", row.symbol, \"  \", row.decision,",
  "    \"\\n    price      $\", centsToUsd(row.priceCents),",
  "    \"\\n    samples    \", fromInt(row.samples),",
  "    \"\\n    mean       $\", centsToUsd(row.mean),",
  "    \"\\n    std dev    $\", centsToUsd(row.stddev),",
  "    \"\\n    z-score    \", signedCentis(row.zscore), \" sigma\",",
  "    \"\\n    EMA(5)     $\", centsToUsd(row.emaFast),",
  "    \"\\n    EMA(20)    $\", centsToUsd(row.emaSlow),",
  "    \"\\n    slope      \", fromInt(row.slope), \" cents/step\",",
  "    \"\\n    range pos  \", fromInt(row.rangePos), \"% of [lo,hi]\",",
  "    \"\\n    momentum   \", fromInt(row.momentum), \" cents\",",
  "    \"\\n    score      \", fromInt(row.score), \"  (threshold \", fromInt(threshold), \")\",",
  "    \"\\n    decision   \", row.decision, \"  =>  \", explainDecision(row.score, threshold, row.decision),",
  "    \"\\n    saved      signals#\", savedId,",
  "    \"\\n    alert      \", alertStatus",
  "  ])",
  "",
  "persistSignal : Json -> String",
  "persistSignal row = dbInsert(\"signals\", row)",
  "",
  "isActionable : Json -> Bool",
  "isActionable row =",
  "  if row.decision == \"BUY\" then True",
  "  else if row.decision == \"SELL\" then True",
  "  else False",
  "",
  "tickOneAsset : String -> String -> String",
  "tickOneAsset acc sym =",
  "  let trimmed = trim(sym) in",
  "  if strLength(trimmed) == 0 then acc",
  "  else",
  "    let prevCsv = histCsvOrEmpty(trimmed) in",
  "    let px = fetchPriceCents(trimmed) in",
  "    let csv = boundedHistCsv(240, prevCsv, px) in",
  "    let _save = saveHistCsv(trimmed, csv) in",
  "    let window = lastN(20, parseCsvInts(csv)) in",
  "    let threshold = __INPUT_signalThreshold__ in",
  "    let bias = __INPUT_positionBias__ in",
  "    let bot = __INPUT_telegramBotToken__ in",
  "    let chat = __INPUT_telegramChatId__ in",
  "    let row = decisionForAsset(threshold, bias, trimmed, window) in",
  "    let savedId = persistSignal(row) in",
  "    let shouldNotify = isActionable(row) in",
  "    let alertText = joinStr([trimmed, \" \", row.decision, \" @ $\", centsToUsd(px)]) in",
  "    let alertStatus =",
  "      if shouldNotify then strConcat(\"sent -> \", notifyTelegram(bot, chat, alertText))",
  "      else \"skipped (HOLD, not actionable)\" in",
  "    let detail = assetDetail(row, threshold, savedId, alertStatus) in",
  "    if strLength(acc) == 0 then detail else strConcat(acc, strConcat(\"\\n\\n\", detail))",
  "",
  "runTick : Unit -> String",
  "runTick _ =",
  "  let assets = split(__INPUT_assetsCsv__, \",\") in",
  "  let body = foldl(tickOneAsset, \"\", assets) in",
  "  if strLength(body) == 0 then \"No assets to evaluate.\"",
  "  else strConcat(\"=== Verdict tick: statistical multi-asset decisions ===\\n\\n\", body)",
  "",
  "-- Endless loop: run one tick, then sleep 5s (the cadence is in the cell, not",
  "-- the environment). The notebook re-runs this cell after each sleep.",
  "main : String",
  "main = loopEvery(5000, runTick)",
];
