/** Default notebook cell 2 (backtest + simReport display). */
export const DEFAULT_NOTEBOOK_SIM_CELL_LINES = [
  'module Backtest exposing (simReport)',
  'import Market exposing (..)',
  '',
  '-- Back-test example: pulls ~200 hourly candles from Binance klines.',
  '-- Imports Market.verdict for Binance parsing, indicators, scoring, and formatting.',
  '',
  '-- Prefer Binance history; use the shared cache csv only as offline fallback.',
  'backtestPricesCents : String -> List Int',
  'backtestPricesCents sym =',
  '  let remote = fetchHistPricesCents(sym) in',
  '  if length(remote) > 0 then remote else parseCsvInts(histCsvOrEmpty(sym))',
  '',
  '-- Market.decisionFromScore over a trailing window, expressed as a position: +1/-1/0.',
  'strategyPos : List Int -> Int',
  'strategyPos window =',
  '  if isEmpty(window) then 0',
  '  else',
  '    let bias = __INPUT_positionBias__ in',
  '    let threshold = __INPUT_signalThreshold__ in',
  '    let sc = scoreOf(zScoreOf(window), emaOf(5, window), emaOf(20, window), slopeOf(window), momentumOf(window), bias) in',
  '    let d = decisionFromScore(sc, threshold) in',
  '    if d == "BUY" then 1 else if d == "SELL" then (0 - 1) else 0',
  '',
  '-- Walk-forward backtest: $1000 compounded by cell 1 strategy, recording the',
  '-- equity curve, position timeline, and bars where it BUYS / SELLS.',
  'finStep : { hist : List Int, i : Int, prevPx : Int, prevPos : Int, eq : Int, eqCurve : List Int, posCurve : List Int, buyX : List Int, buyY : List Int, sellX : List Int, sellY : List Int, trades : Int } -> Int -> { hist : List Int, i : Int, prevPx : Int, prevPos : Int, eq : Int, eqCurve : List Int, posCurve : List Int, buyX : List Int, buyY : List Int, sellX : List Int, sellY : List Int, trades : Int }',
  'finStep a px =',
  '  let pos = strategyPos(lastN(20, a.hist)) in',
  '  let neweq = if a.prevPx == 0 then a.eq else a.eq + (pos * a.eq * (px - a.prevPx)) / a.prevPx in',
  '  let isBuy = if a.prevPos > 0 then False else pos > 0 in',
  '  let isSell = if a.prevPos > 0 then if pos > 0 then False else True else False in',
  '  { hist = append(a.hist, px), i = a.i + 1, prevPx = px, prevPos = pos, eq = neweq,',
  '    eqCurve = append(a.eqCurve, neweq), posCurve = append(a.posCurve, pos),',
  '    buyX = if isBuy then append(a.buyX, a.i) else a.buyX,',
  '    buyY = if isBuy then append(a.buyY, px) else a.buyY,',
  '    sellX = if isSell then append(a.sellX, a.i) else a.sellX,',
  '    sellY = if isSell then append(a.sellY, px) else a.sellY,',
  '    trades = if isBuy then a.trades + 1 else a.trades }',
  '',
  'finSim : List Int -> { hist : List Int, i : Int, prevPx : Int, prevPos : Int, eq : Int, eqCurve : List Int, posCurve : List Int, buyX : List Int, buyY : List Int, sellX : List Int, sellY : List Int, trades : Int }',
  'finSim prices =',
  '  foldl(finStep, { hist = [], i = 0, prevPx = 0, prevPos = 0, eq = 100000, eqCurve = [], posCurve = [], buyX = [], buyY = [], sellX = [], sellY = [], trades = 0 }, prices)',
  '',
  '-- Output is composed with the Display library (Plotly charts, text, layout).',
  '-- Nothing about the chart shape is hardcoded in the host: Display builds the',
  '-- Json the generic renderer draws. One titled column per asset, each with a',
  '-- P&L summary and a row of price/equity/position charts.',
  'assetBlock : String -> Json',
  'assetBlock sym =',
  '  let prices = backtestPricesCents(sym) in',
  '  let r = finSim(prices) in',
  '  let xs = indicesOf(prices) in',
  '  let finalEq = lastInt(r.eqCurve) in',
  '  let pnl = finalEq - 100000 in',
  '  let summary = strConcat("final $", strConcat(centsToUsd(finalEq), strConcat("  ·  P&L $", strConcat(centsToUsd(pnl), strConcat("  ·  ", strConcat(fromInt(r.trades), strConcat(" trades · ", strConcat(fromInt(length(prices)), " bars")))))))) in',
  '  dCol(sym, [',
  '    dText(summary),',
  '    dRow([',
  '      dChartY("Price + trades", [',
  '        dLine("price", xs, prices, "#94a3b8"),',
  '        dMarkers("BUY", r.buyX, r.buyY, "#34d399", "triangle-up"),',
  '        dMarkers("SELL", r.sellX, r.sellY, "#f87171", "triangle-down") ], "bar", "cents"),',
  '      dChartY("Equity ($1000 start)", [ dArea("equity", xs, r.eqCurve, "#fbbf24") ], "bar", "cents"),',
  '      dChartY("Position", [ dStep("position", xs, r.posCurve, "#a78bfa") ], "bar", "+1/0/-1")',
  '    ])',
  '  ])',
  '',
  '-- One col block per asset; stack them vertically in the report.',
  'reportAcc : List Json -> String -> List Json',
  'reportAcc acc sym =',
  '  let t = trim(sym) in',
  '  if strLength(t) == 0 then acc else concat(acc, [ assetBlock(t) ])',
  '',
  'simReport : Json',
  'simReport = dStack(foldl(reportAcc, [], split(__INPUT_assetsCsv__, ",")))',
];
