/** Default notebook cell 2 (incremental walk-forward backtest + charts). */

// The simulator's walk-forward accumulator. Verdict has no record type alias,
// so the full shape is repeated in every signature — keep the SOURCE DRY by
// templating this one constant into each `: <state>` annotation below.
const S =
  "{ simseq : Int, i : Int, prevPx : Int, prevPos : Int, eq : Int, trades : Int, window : List Int, pxCurve : List Int, eqCurve : List Int, posCurve : List Int, xCurve : List Int, buyX : List Int, buyY : List Int, sellX : List Int, sellY : List Int }";

export const DEFAULT_NOTEBOOK_SIM_CELL_LINES = [
  'module Backtest exposing (simulate)',
  'import Market exposing (..)',
  'import Display exposing (..)',
  'import IDE exposing (..)',
  '',
  '-- Simulator cell: an INCREMENTAL walk-forward backtest. The producer cell',
  '-- publishes a monotonic bar counter (seq:<sym>); this cell persists its own',
  '-- accumulator (sim:<sym>) and each loop folds the strategy over only the',
  '-- bars added since its last checkpoint — never re-running the whole history.',
  '-- curveCap controls the recorded equity/position curve: 0 = unbounded (full',
  '-- record), N = keep just the last N bars. Both modes share this one code path',
  '-- and run identically off the IDE. Charts come from the Display library.',
  '',
  '-- Market.decisionFromScore over a trailing window, expressed as a position: +1/-1/0.',
  'strategyPos : List Int -> Int',
  'strategyPos window =',
  '  if isEmpty(window) then 0',
  '  else',
  '    let bias = __INPUT_positionBias__ in',
  '    let threshold = __INPUT_signalThreshold__ in',
  '    let sc = scoreOf(zScoreOf(window), emaOf(5, window), emaOf(20, window), slopeOf(window), momentumOf(window), bias) in',
  '    let d = decisionFromScore(sc, threshold) in',
  '    if d == "BUY" then 1 else if d == "SELL" then (0 - 1) else 0',
  '',
  '-- Cold-start price source (used only before the producer has published any',
  "-- bars): the producer's live history if present, else Binance klines.",
  'backtestPricesCents : String -> List Int',
  'backtestPricesCents sym =',
  '  let live = csvToInts(histCsvOrEmpty(sym)) in',
  '  if length(live) > 0 then live else fetchHistPricesCents(sym)',
  '',
  '-- Empty walk-forward state: $1000 start (in cents), no bars processed yet.',
  "-- Takes Unit (not a nullary value) so it stays a helper, not a cell output.",
  `initState : Unit -> ${S}`,
  'initState _ =',
  '  { simseq = 0, i = 0, prevPx = 0, prevPos = 0, eq = 100000, trades = 0,',
  '    window = [], pxCurve = [], eqCurve = [], posCurve = [], xCurve = [],',
  '    buyX = [], buyY = [], sellX = [], sellY = [] }',
  '',
  '-- One walk-forward step: advance equity/position by one fresh price. The',
  '-- strategy window is bounded to the last 20 prices, so a step is O(1) in the',
  '-- run length — the whole point of going incremental.',
  `finStep : ${S} -> Int -> ${S}`,
  'finStep a px =',
  '  let win = lastN(20, append(a.window, px)) in',
  '  let pos = strategyPos(win) in',
  '  let neweq = if a.prevPx == 0 then a.eq else a.eq + (pos * a.eq * (px - a.prevPx)) / a.prevPx in',
  '  let isBuy = if a.prevPos > 0 then False else pos > 0 in',
  '  let isSell = if a.prevPos > 0 then (if pos > 0 then False else True) else False in',
  '  { simseq = a.simseq, i = a.i + 1, prevPx = px, prevPos = pos, eq = neweq,',
  '    trades = if isBuy then a.trades + 1 else a.trades, window = win,',
  '    pxCurve = append(a.pxCurve, px), eqCurve = append(a.eqCurve, neweq),',
  '    posCurve = append(a.posCurve, pos), xCurve = append(a.xCurve, a.i),',
  '    buyX = if isBuy then append(a.buyX, a.i) else a.buyX,',
  '    buyY = if isBuy then append(a.buyY, px) else a.buyY,',
  '    sellX = if isSell then append(a.sellX, a.i) else a.sellX,',
  '    sellY = if isSell then append(a.sellY, px) else a.sellY }',
  '',
  '-- Count ints strictly below a threshold (trade markers are appended in',
  '-- ascending bar order, so this is the prefix to drop when the curve is capped).',
  'countLT : Int -> List Int -> Int',
  'countLT m xs = (foldl(cntAcc, { m = m, c = 0 }, xs)).c',
  '',
  'cntAcc : { m : Int, c : Int } -> Int -> { m : Int, c : Int }',
  'cntAcc a x = { m = a.m, c = if x < a.m then a.c + 1 else a.c }',
  '',
  '-- Cap the recorded curves to the last `cap` bars (cap <= 0 = unbounded) and',
  '-- stamp the processed checkpoint. Markers before the visible window drop off.',
  `capAndStamp : Int -> Int -> ${S} -> ${S}`,
  'capAndStamp cap seq s =',
  '  let doCap = cap > 0 in',
  '  let xs = if doCap then capInts(cap, s.xCurve) else s.xCurve in',
  '  let minX = withDefault(0, head(xs)) in',
  '  let nb = if doCap then countLT(minX, s.buyX) else 0 in',
  '  let ns = if doCap then countLT(minX, s.sellX) else 0 in',
  '  { simseq = seq, i = s.i, prevPx = s.prevPx, prevPos = s.prevPos, eq = s.eq,',
  '    trades = s.trades, window = s.window,',
  '    pxCurve = if doCap then capInts(cap, s.pxCurve) else s.pxCurve,',
  '    eqCurve = if doCap then capInts(cap, s.eqCurve) else s.eqCurve,',
  '    posCurve = if doCap then capInts(cap, s.posCurve) else s.posCurve,',
  '    xCurve = xs,',
  '    buyX = drop(nb, s.buyX), buyY = drop(nb, s.buyY),',
  '    sellX = drop(ns, s.sellX), sellY = drop(ns, s.sellY) }',
  '',
  '-- Persisted state <-> string: pipe-separated CSV sections (scalars first).',
  `serializeState : ${S} -> String`,
  'serializeState s =',
  '  joinStr([ intsToCsv([s.simseq, s.i, s.prevPx, s.prevPos, s.eq, s.trades]), "|",',
  '    intsToCsv(s.window), "|", intsToCsv(s.pxCurve), "|", intsToCsv(s.eqCurve), "|",',
  '    intsToCsv(s.posCurve), "|", intsToCsv(s.xCurve), "|", intsToCsv(s.buyX), "|",',
  '    intsToCsv(s.buyY), "|", intsToCsv(s.sellX), "|", intsToCsv(s.sellY) ])',
  '',
  'nthInt : Int -> List Int -> Int',
  'nthInt n xs = withDefault(0, head(drop(n, xs)))',
  '',
  `loadState : String -> ${S}`,
  'loadState sym =',
  '  let raw = cacheStrOr(simKey(sym)) in',
  '  if strLength(raw) == 0 then initState(unit)',
  '  else',
  '    let p = split(raw, "|") in',
  '    let sc = csvToInts(nthStr(0, p)) in',
  '    { simseq = nthInt(0, sc), i = nthInt(1, sc), prevPx = nthInt(2, sc),',
  '      prevPos = nthInt(3, sc), eq = nthInt(4, sc), trades = nthInt(5, sc),',
  '      window = csvToInts(nthStr(1, p)), pxCurve = csvToInts(nthStr(2, p)),',
  '      eqCurve = csvToInts(nthStr(3, p)), posCurve = csvToInts(nthStr(4, p)),',
  '      xCurve = csvToInts(nthStr(5, p)), buyX = csvToInts(nthStr(6, p)),',
  '      buyY = csvToInts(nthStr(7, p)), sellX = csvToInts(nthStr(8, p)),',
  '      sellY = csvToInts(nthStr(9, p)) }',
  '',
  "-- Cold start (producer hasn't published a bar count yet): a one-shot full",
  '-- backtest for display, not persisted. Switches to incremental once seq > 0.',
  `bootstrap : String -> ${S}`,
  'bootstrap sym = capAndStamp(__INPUT_curveCap__, 0, foldl(finStep, initState(unit), backtestPricesCents(sym)))',
  '',
  '-- Incremental step: fold only the bars added since our checkpoint, persist.',
  `processAsset : String -> ${S}`,
  'processAsset sym =',
  '  let seq = barSeqOf(sym) in',
  '  if seq == 0 then bootstrap(sym)',
  '  else',
  '    let st = loadState(sym) in',
  '    let delta = seq - st.simseq in',
  '    if delta < 1 then st',
  '    else',
  '      let fresh = lastN(delta, csvToInts(histCsvOrEmpty(sym))) in',
  '      let result = capAndStamp(__INPUT_curveCap__, seq, foldl(finStep, st, fresh)) in',
  '      let _save = cachePutStr(simKey(sym), serializeState(result)) in',
  '      result',
  '',
  '-- Output is composed with the Display library: one titled column per asset,',
  '-- a P&L summary and a row of price/equity/position charts. Nothing about the',
  '-- chart shape is hardcoded in the host — Display builds the Json to render.',
  'assetBlock : String -> Json',
  'assetBlock sym =',
  '  let r = processAsset(sym) in',
  '  let finalEq = if isEmpty(r.eqCurve) then 100000 else lastInt(r.eqCurve) in',
  '  let pnl = finalEq - 100000 in',
  '  let summary = joinStr(["final $", centsToUsd(finalEq), "  ·  P&L $", centsToUsd(pnl), "  ·  ", fromInt(r.trades), " trades · ", fromInt(r.i), " bars"]) in',
  '  dCol(sym, [',
  '    dText(summary),',
  '    dRow([',
  '      dChartY("Price + trades", [',
  '        dLine("price", r.xCurve, r.pxCurve, "#94a3b8"),',
  '        dMarkers("BUY", r.buyX, r.buyY, "#34d399", "triangle-up"),',
  '        dMarkers("SELL", r.sellX, r.sellY, "#f87171", "triangle-down") ], "bar", "cents"),',
  '      dChartY("Equity ($1000 start)", [ dArea("equity", r.xCurve, r.eqCurve, "#fbbf24") ], "bar", "cents"),',
  '      dChartY("Position", [ dStep("position", r.xCurve, r.posCurve, "#a78bfa") ], "bar", "+1/0/-1")',
  '    ])',
  '  ])',
  '',
  '-- One col block per asset; stack them vertically in the report.',
  'reportAcc : List Json -> String -> List Json',
  'reportAcc acc sym =',
  '  let t = trim(sym) in',
  '  if strLength(t) == 0 then acc else concat(acc, [ assetBlock(t) ])',
  '',
  'buildReport : Unit -> Json',
  'buildReport _ = dStack(foldl(reportAcc, [], split(__INPUT_assetsCsv__, ",")))',
  '',
  '-- Endless actor: every loop-interval it advances the incremental backtest and',
  '-- sends the refreshed report to its own output (renderEvery → emit). Stop ends it.',
  'simulate : Unit',
  'simulate = renderEvery(__INPUT_loopIntervalMs__, buildReport)',
];
