/** Default notebook cell 2 (backtest + simReport display). */
export const DEFAULT_NOTEBOOK_SIM_CELL_LINES = [
  '-- Back-test example: pulls ~200 hourly candles from Binance klines.',
  '-- Uses the same strategy helpers as cell 1.',
  '',
  '-- Binance klines: parse close prices from the JSON array without json.* builtins.',
  'binanceKlinesUrl : String -> String',
  'binanceKlinesUrl sym =',
  '  strConcat(strConcat("https://api.binance.com/api/v3/klines?symbol=", binanceSymbol(sym)), "&interval=1h&limit=200")',
  '',
  'klineCloseCents : String -> Int',
  'klineCloseCents chunk =',
  '  dollarsToCents(withDefault("0", head(drop(3, split(chunk, "\\",\\"")))))',
  '',
  'pushKlineChunk : List Int -> String -> List Int',
  'pushKlineChunk acc chunk =',
  '  if strLength(chunk) == 0 then acc else append(acc, klineCloseCents(chunk))',
  '',
  'parseKlinesBody : String -> List Int',
  'parseKlinesBody body = foldl(pushKlineChunk, [], split(body, "],["))',
  '',
  'fetchHistPricesCents : String -> List Int',
  'fetchHistPricesCents sym =',
  '  let res = httpGet(binanceKlinesUrl(sym)) in',
  '  if res.ok then parseKlinesBody(res.body) else []',
  '',
  '-- Prefer Binance history; use cell 1 cache csv only as offline fallback.',
  'backtestPricesCents : String -> List Int',
  'backtestPricesCents sym =',
  '  let remote = fetchHistPricesCents(sym) in',
  '  if length(remote) > 0 then remote else parseCsvInts(histCsvOrEmpty(sym))',
  '',
  '-- Cell 1\'s decision over a trailing window, expressed as a position: +1/-1/0.',
  'strategyPos : List Int -> Int',
  'strategyPos window =',
  '  if isEmpty(window) then 0',
  '  else',
  '    let bias = __INPUT_positionBias__ in',
  '    let threshold = __INPUT_signalThreshold__ in',
  '    let sc = scoreOf(zScoreOf(window), emaOf(5, window), emaOf(20, window), slopeOf(window), momentumOf(window), bias) in',
  '    let d = decisionFromScore(sc, threshold) in',
  '    if d == "BUY" then 1 else if d == "SELL" then (0 - 1) else 0',
  '',
  '-- 0,1,2,... index for the x axis (one per sample).',
  'idxAcc : { i : Int, out : List Int } -> Int -> { i : Int, out : List Int }',
  'idxAcc a _ = { i = a.i + 1, out = append(a.out, a.i) }',
  '',
  'indicesOf : List Int -> List Int',
  'indicesOf xs = (foldl(idxAcc, { i = 0, out = [] }, xs)).out',
  '',
  '-- Walk-forward backtest: $1000 compounded by cell 1 strategy, recording the',
  '-- equity curve, position timeline, and bars where it BUYS / SELLS.',
  'finStep : { hist : List Int, i : Int, prevPx : Int, prevPos : Int, eq : Int, eqCurve : List Int, posCurve : List Int, buyX : List Int, buyY : List Int, sellX : List Int, sellY : List Int, trades : Int } -> Int -> { hist : List Int, i : Int, prevPx : Int, prevPos : Int, eq : Int, eqCurve : List Int, posCurve : List Int, buyX : List Int, buyY : List Int, sellX : List Int, sellY : List Int, trades : Int }',
  'finStep a px =',
  '  let pos = strategyPos(lastN(20, a.hist)) in',
  '  let neweq = if a.prevPx == 0 then a.eq else a.eq + (pos * a.eq * (px - a.prevPx)) / a.prevPx in',
  '  let isBuy = if a.prevPos > 0 then False else pos > 0 in',
  '  let isSell = if a.prevPos > 0 then if pos > 0 then False else True else False in',
  '  { hist = append(a.hist, px), i = a.i + 1, prevPx = px, prevPos = pos, eq = neweq,',
  '    eqCurve = append(a.eqCurve, neweq), posCurve = append(a.posCurve, pos),',
  '    buyX = if isBuy then append(a.buyX, a.i) else a.buyX,',
  '    buyY = if isBuy then append(a.buyY, px) else a.buyY,',
  '    sellX = if isSell then append(a.sellX, a.i) else a.sellX,',
  '    sellY = if isSell then append(a.sellY, px) else a.sellY,',
  '    trades = if isBuy then a.trades + 1 else a.trades }',
  '',
  'finSim : List Int -> { hist : List Int, i : Int, prevPx : Int, prevPos : Int, eq : Int, eqCurve : List Int, posCurve : List Int, buyX : List Int, buyY : List Int, sellX : List Int, sellY : List Int, trades : Int }',
  'finSim prices =',
  '  foldl(finStep, { hist = [], i = 0, prevPx = 0, prevPos = 0, eq = 100000, eqCurve = [], posCurve = [], buyX = [], buyY = [], sellX = [], sellY = [], trades = 0 }, prices)',
  '',
  '-- Display layout: stack, then col per asset, row of charts, then leaves.',
  'assetBlock : String -> Json',
  'assetBlock sym =',
  '  let prices = backtestPricesCents(sym) in',
  '  let r = finSim(prices) in',
  '  let xs = indicesOf(prices) in',
  '  let finalEq = lastInt(r.eqCurve) in',
  '  let pnl = finalEq - 100000 in',
  '  let summary = strConcat("final $", strConcat(centsToUsd(finalEq), strConcat("  ·  P&L $", strConcat(centsToUsd(pnl), strConcat("  ·  ", strConcat(fromInt(r.trades), strConcat(" trades · ", strConcat(fromInt(length(prices)), " bars")))))))) in',
  '  { kind = "col", title = sym, text = "", traces = [], xaxis = { title = "" }, yaxis = { title = "" }, yaxis2 = { title = "" }, items = [',
  '    { kind = "text", title = "", text = summary, traces = [], xaxis = { title = "" }, yaxis = { title = "" }, yaxis2 = { title = "" }, items = [] },',
  '    { kind = "row", title = "", text = "", traces = [], xaxis = { title = "" }, yaxis = { title = "" }, yaxis2 = { title = "" }, items = [',
  '      { kind = "chart", title = "Price + trades", text = "",',
  '        traces = [',
  '          { name = "price", kind = "line", x = xs, y = prices, axis = "y", color = "#94a3b8", symbol = "" },',
  '          { name = "BUY", kind = "markers", x = r.buyX, y = r.buyY, axis = "y", color = "#34d399", symbol = "triangle-up" },',
  '          { name = "SELL", kind = "markers", x = r.sellX, y = r.sellY, axis = "y", color = "#f87171", symbol = "triangle-down" } ],',
  '        xaxis = { title = "bar" }, yaxis = { title = "cents" }, yaxis2 = { title = "" } },',
  '      { kind = "chart", title = "Equity ($1000 start)", text = "",',
  '        traces = [',
  '          { name = "equity", kind = "area", x = xs, y = r.eqCurve, axis = "y", color = "#fbbf24", symbol = "" } ],',
  '        xaxis = { title = "bar" }, yaxis = { title = "cents" }, yaxis2 = { title = "" } },',
  '      { kind = "chart", title = "Position", text = "",',
  '        traces = [',
  '          { name = "position", kind = "step", x = xs, y = r.posCurve, axis = "y", color = "#a78bfa", symbol = "" } ],',
  '        xaxis = { title = "bar" }, yaxis = { title = "+1/0/-1" }, yaxis2 = { title = "" } }',
  '    ] }',
  '  ] }',
  '',
  '-- One col block per asset; stack them vertically in the report.',
  'reportAcc : List Json -> String -> List Json',
  'reportAcc acc sym =',
  '  let t = trim(sym) in',
  '  if strLength(t) == 0 then acc else concat(acc, [ assetBlock(t) ])',
  '',
  'simReport : Json',
  'simReport = { kind = "stack", title = "", text = "", traces = [], xaxis = { title = "" }, yaxis = { title = "" }, yaxis2 = { title = "" }, items = foldl(reportAcc, [], split(__INPUT_assetsCsv__, ",")) }',
];
